apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cmed-frontend-security-headers
  namespace: {{ .Values.namespace }}
  labels:
    app: cmed-frontend
    chart: "cmed-frontend-1.0.0"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    frameDeny: false
    customFrameOptionsValue: "SAMEORIGIN"
    customResponseHeaders:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "SAMEORIGIN"
      X-XSS-Protection: "1; mode=block"
      # content-security-policy removed for now