apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmed-postgresql-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: cmed-postgresql
    chart: "cmed-postgresql-1.0.0"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
